version: '3.4'

services:
  queflitymvc.web:
    image: ${DOCKER_REGISTRY-}queflitymvcweb
    build:
      context: .
      dockerfile: QueflityMVC/Dockerfile
    ports:
      - "5000:80"
    environment:
          - OAUTH_GOOGLE_CLIENT_ID=313258013736-cjneh6omvfrfjne2sr0euhpbi17n55du.apps.googleusercontent.com
          - OAUTH_GOOGLE_CLIENT_SECRET=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
          - DB_CONNECTION_STRING=Server=sql_server2022;Database=QueflityMvc;User Id=SA;Password=Lf5892dENz;MultipleActiveResultSets=true;TrustServerCertificate=true
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Lf5892dENz