version: '3.4'

services:
  queflitymvc.web:
    image: ${DOCKER_REGISTRY-}queflitymvcweb
    build:
      context: .
      dockerfile: QueflityMVC/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
          - OAUTH_GOOGLE_CLIENT_ID=313258013736-cjneh6omvfrfjne2sr0euhpbi17n55du.apps.googleusercontent.com
          - OAUTH_GOOGLE_CLIENT_SECRET=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
          - DB_CONNECTION_STRING=Server=queflity_db;Database=QueflityMvc;User Id=SA;Password=Lf5892dENz;MultipleActiveResultSets=true;TrustServerCertificate=true
          - ASPNETCORE_URLS=https://+:5001;http://+:5000
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: queflity_db
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Lf5892dENz