// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueflityMVC.Persistence;

#nullable disable

namespace QueflityMVC.Persistence.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComponentItem", b =>
                {
                    b.Property<int>("ComponentsId")
                        .HasColumnType("int");

                    b.Property<int>("ItemsId")
                        .HasColumnType("int");

                    b.HasKey("ComponentsId", "ItemsId");

                    b.HasIndex("ItemsId");

                    b.ToTable("ComponentItem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Computers"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kids"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Electronics"
                        });
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rubber"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Metal"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Granite"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Frozen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Wooden"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Concrete"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fresh"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Steel"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Soft"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Cotton"
                        });
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<long>("ItemsAmount")
                        .HasColumnType("bigint");

                    b.Property<int>("KitId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerItem")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("KitId");

                    b.ToTable("SetElements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 6,
                            ItemsAmount = 4L,
                            KitId = 14,
                            PricePerItem = 6.52m
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 1,
                            ItemsAmount = 7L,
                            KitId = 16,
                            PricePerItem = 35.46m
                        },
                        new
                        {
                            Id = 3,
                            ItemId = 4,
                            ItemsAmount = 9L,
                            KitId = 11,
                            PricePerItem = 3.57m
                        },
                        new
                        {
                            Id = 4,
                            ItemId = 10,
                            ItemsAmount = 9L,
                            KitId = 13,
                            PricePerItem = 52.58m
                        },
                        new
                        {
                            Id = 5,
                            ItemId = 8,
                            ItemsAmount = 3L,
                            KitId = 12,
                            PricePerItem = 10.68m
                        },
                        new
                        {
                            Id = 6,
                            ItemId = 1,
                            ItemsAmount = 9L,
                            KitId = 20,
                            PricePerItem = 45.29m
                        },
                        new
                        {
                            Id = 7,
                            ItemId = 10,
                            ItemsAmount = 6L,
                            KitId = 19,
                            PricePerItem = 25.58m
                        },
                        new
                        {
                            Id = 9,
                            ItemId = 8,
                            ItemsAmount = 6L,
                            KitId = 15,
                            PricePerItem = 159.77m
                        },
                        new
                        {
                            Id = 10,
                            ItemId = 10,
                            ItemsAmount = 2L,
                            KitId = 12,
                            PricePerItem = 198.25m
                        },
                        new
                        {
                            Id = 11,
                            ItemId = 6,
                            ItemsAmount = 4L,
                            KitId = 19,
                            PricePerItem = 14.14m
                        },
                        new
                        {
                            Id = 13,
                            ItemId = 7,
                            ItemsAmount = 2L,
                            KitId = 13,
                            PricePerItem = 15.70m
                        },
                        new
                        {
                            Id = 14,
                            ItemId = 9,
                            ItemsAmount = 9L,
                            KitId = 14,
                            PricePerItem = 29.35m
                        },
                        new
                        {
                            Id = 15,
                            ItemId = 7,
                            ItemsAmount = 6L,
                            KitId = 17,
                            PricePerItem = 121.91m
                        },
                        new
                        {
                            Id = 16,
                            ItemId = 3,
                            ItemsAmount = 2L,
                            KitId = 20,
                            PricePerItem = 87.43m
                        },
                        new
                        {
                            Id = 17,
                            ItemId = 5,
                            ItemsAmount = 4L,
                            KitId = 13,
                            PricePerItem = 81.68m
                        });
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltDescription = "aut",
                            FileUrl = "https://picsum.photos/640/480/?image=491"
                        },
                        new
                        {
                            Id = 2,
                            AltDescription = "quam",
                            FileUrl = "https://picsum.photos/640/480/?image=251"
                        },
                        new
                        {
                            Id = 3,
                            AltDescription = "quam",
                            FileUrl = "https://picsum.photos/640/480/?image=13"
                        },
                        new
                        {
                            Id = 4,
                            AltDescription = "voluptatem",
                            FileUrl = "https://picsum.photos/640/480/?image=674"
                        },
                        new
                        {
                            Id = 5,
                            AltDescription = "nulla",
                            FileUrl = "https://picsum.photos/640/480/?image=186"
                        },
                        new
                        {
                            Id = 6,
                            AltDescription = "voluptatibus",
                            FileUrl = "https://picsum.photos/640/480/?image=748"
                        },
                        new
                        {
                            Id = 7,
                            AltDescription = "aut",
                            FileUrl = "https://picsum.photos/640/480/?image=95"
                        },
                        new
                        {
                            Id = 8,
                            AltDescription = "quis",
                            FileUrl = "https://picsum.photos/640/480/?image=854"
                        },
                        new
                        {
                            Id = 9,
                            AltDescription = "eius",
                            FileUrl = "https://picsum.photos/640/480/?image=868"
                        },
                        new
                        {
                            Id = 10,
                            AltDescription = "eum",
                            FileUrl = "https://picsum.photos/640/480/?image=970"
                        },
                        new
                        {
                            Id = 11,
                            AltDescription = "rerum",
                            FileUrl = "https://picsum.photos/640/480/?image=367"
                        },
                        new
                        {
                            Id = 12,
                            AltDescription = "rem",
                            FileUrl = "https://picsum.photos/640/480/?image=659"
                        },
                        new
                        {
                            Id = 13,
                            AltDescription = "et",
                            FileUrl = "https://picsum.photos/640/480/?image=822"
                        },
                        new
                        {
                            Id = 14,
                            AltDescription = "molestiae",
                            FileUrl = "https://picsum.photos/640/480/?image=732"
                        },
                        new
                        {
                            Id = 15,
                            AltDescription = "aut",
                            FileUrl = "https://picsum.photos/640/480/?image=715"
                        },
                        new
                        {
                            Id = 16,
                            AltDescription = "rerum",
                            FileUrl = "https://picsum.photos/640/480/?image=113"
                        },
                        new
                        {
                            Id = 17,
                            AltDescription = "alias",
                            FileUrl = "https://picsum.photos/640/480/?image=537"
                        },
                        new
                        {
                            Id = 18,
                            AltDescription = "sit",
                            FileUrl = "https://picsum.photos/640/480/?image=3"
                        },
                        new
                        {
                            Id = 19,
                            AltDescription = "accusamus",
                            FileUrl = "https://picsum.photos/640/480/?image=990"
                        },
                        new
                        {
                            Id = 20,
                            AltDescription = "dicta",
                            FileUrl = "https://picsum.photos/640/480/?image=838"
                        });
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrderNo")
                        .HasColumnType("bigint");

                    b.Property<bool>("ShouldBeShown")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Product");

                    b.HasDiscriminator().HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Item", b =>
                {
                    b.HasBaseType("QueflityMVC.Domain.Models.Product");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasIndex("CategoryId");

                    b.HasDiscriminator().HasValue("Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageId = 1,
                            Name = "Practical Metal Cheese",
                            OrderNo = 8L,
                            ShouldBeShown = true,
                            CategoryId = 4,
                            Price = 47.19m
                        },
                        new
                        {
                            Id = 2,
                            ImageId = 2,
                            Name = "Incredible Rubber Hat",
                            OrderNo = 7L,
                            ShouldBeShown = true,
                            CategoryId = 5,
                            Price = 47.33m
                        },
                        new
                        {
                            Id = 3,
                            ImageId = 3,
                            Name = "Awesome Wooden Gloves",
                            ShouldBeShown = false,
                            CategoryId = 4,
                            Price = 2.38m
                        },
                        new
                        {
                            Id = 4,
                            ImageId = 4,
                            Name = "Practical Plastic Cheese",
                            ShouldBeShown = false,
                            CategoryId = 5,
                            Price = 77.42m
                        },
                        new
                        {
                            Id = 5,
                            ImageId = 5,
                            Name = "Incredible Fresh Chips",
                            OrderNo = 4L,
                            ShouldBeShown = true,
                            CategoryId = 5,
                            Price = 29.71m
                        },
                        new
                        {
                            Id = 6,
                            ImageId = 6,
                            Name = "Rustic Plastic Shoes",
                            ShouldBeShown = false,
                            CategoryId = 5,
                            Price = 3.17m
                        },
                        new
                        {
                            Id = 7,
                            ImageId = 7,
                            Name = "Incredible Concrete Chips",
                            ShouldBeShown = false,
                            CategoryId = 2,
                            Price = 25.32m
                        },
                        new
                        {
                            Id = 8,
                            ImageId = 8,
                            Name = "Intelligent Frozen Hat",
                            OrderNo = 6L,
                            ShouldBeShown = true,
                            CategoryId = 2,
                            Price = 38.57m
                        },
                        new
                        {
                            Id = 9,
                            ImageId = 9,
                            Name = "Handmade Cotton Bike",
                            ShouldBeShown = false,
                            CategoryId = 4,
                            Price = 15.80m
                        },
                        new
                        {
                            Id = 10,
                            ImageId = 10,
                            Name = "Ergonomic Granite Bike",
                            OrderNo = 2L,
                            ShouldBeShown = true,
                            CategoryId = 4,
                            Price = 4.73m
                        });
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Kit", b =>
                {
                    b.HasBaseType("QueflityMVC.Domain.Models.Product");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.HasIndex("ItemId");

                    b.HasDiscriminator().HasValue("Kit");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            ImageId = 11,
                            Name = "Awesome Metal Towels",
                            OrderNo = 5L,
                            ShouldBeShown = true,
                            Description = "Nostrum sint aut autem placeat temporibus eum."
                        },
                        new
                        {
                            Id = 12,
                            ImageId = 12,
                            Name = "Rustic Metal Sausages",
                            ShouldBeShown = false,
                            Description = "Animi reprehenderit illo velit molestiae qui inventore fugit non."
                        },
                        new
                        {
                            Id = 13,
                            ImageId = 13,
                            Name = "Awesome Steel Ball",
                            OrderNo = 9L,
                            ShouldBeShown = true,
                            Description = "Est saepe expedita nam."
                        },
                        new
                        {
                            Id = 14,
                            ImageId = 14,
                            Name = "Refined Concrete Fish",
                            ShouldBeShown = false,
                            Description = "Omnis velit ut natus minus voluptatem voluptas omnis minima."
                        },
                        new
                        {
                            Id = 15,
                            ImageId = 15,
                            Name = "Sleek Frozen Pizza",
                            ShouldBeShown = false,
                            Description = "Voluptate qui quis."
                        },
                        new
                        {
                            Id = 16,
                            ImageId = 16,
                            Name = "Generic Metal Bike",
                            ShouldBeShown = false,
                            Description = "Repudiandae dolorum porro officiis suscipit voluptates nulla ut."
                        },
                        new
                        {
                            Id = 17,
                            ImageId = 17,
                            Name = "Awesome Steel Soap",
                            OrderNo = 1L,
                            ShouldBeShown = true,
                            Description = "Dicta placeat a porro magnam ad aut ullam accusamus."
                        },
                        new
                        {
                            Id = 18,
                            ImageId = 18,
                            Name = "Generic Soft Keyboard",
                            ShouldBeShown = false,
                            Description = "Officiis sint aut est."
                        },
                        new
                        {
                            Id = 19,
                            ImageId = 19,
                            Name = "Handcrafted Steel Tuna",
                            OrderNo = 0L,
                            ShouldBeShown = true,
                            Description = "Molestiae reiciendis sit blanditiis molestias possimus beatae."
                        },
                        new
                        {
                            Id = 20,
                            ImageId = 20,
                            Name = "Incredible Rubber Pizza",
                            ShouldBeShown = false,
                            Description = "Aperiam sint sequi animi velit."
                        });
                });

            modelBuilder.Entity("ComponentItem", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.Component", null)
                        .WithMany()
                        .HasForeignKey("ComponentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueflityMVC.Domain.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueflityMVC.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Conversation", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueflityMVC.Domain.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Element", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.Item", "Item")
                        .WithMany("SetElements")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueflityMVC.Domain.Models.Kit", "Kit")
                        .WithMany("Elements")
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Kit");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Message", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("QueflityMVC.Domain.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Product", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Item", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Kit", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.Item", null)
                        .WithMany("Kits")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Item", b =>
                {
                    b.Navigation("Kits");

                    b.Navigation("SetElements");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Kit", b =>
                {
                    b.Navigation("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
