// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueflityMVC.Persistence;

#nullable disable

namespace QueflityMVC.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComponentItem", b =>
                {
                    b.Property<int>("ComponentsId")
                        .HasColumnType("int");

                    b.Property<int>("ItemsId")
                        .HasColumnType("int");

                    b.HasKey("ComponentsId", "ItemsId");

                    b.HasIndex("ItemsId");

                    b.ToTable("ComponentItem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QueflityMVC.Domain.Common.BasePurchasableEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("OrderNo")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<bool>("ShouldBeShown")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("BasePurchasableEntity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BasePurchasableEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Grocery"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kids"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jewelery"
                        });
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cotton"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fresh"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Soft"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cotton"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Wooden"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cotton"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Wooden"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Frozen"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Steel"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Plastic"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Soft"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Frozen"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Cotton"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Concrete"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Concrete"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Rubber"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Rubber"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Steel"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Granite"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Wooden"
                        });
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<long>("ItemsAmount")
                        .HasColumnType("bigint");

                    b.Property<int>("KitId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerItem")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("KitId");

                    b.ToTable("SetElements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 10,
                            ItemsAmount = 3L,
                            KitId = 17,
                            PricePerItem = 8.28m
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 6,
                            ItemsAmount = 9L,
                            KitId = 17,
                            PricePerItem = 57.61m
                        },
                        new
                        {
                            Id = 3,
                            ItemId = 7,
                            ItemsAmount = 2L,
                            KitId = 19,
                            PricePerItem = 175.23m
                        },
                        new
                        {
                            Id = 4,
                            ItemId = 2,
                            ItemsAmount = 9L,
                            KitId = 19,
                            PricePerItem = 0.81m
                        },
                        new
                        {
                            Id = 5,
                            ItemId = 1,
                            ItemsAmount = 9L,
                            KitId = 18,
                            PricePerItem = 23.26m
                        },
                        new
                        {
                            Id = 6,
                            ItemId = 3,
                            ItemsAmount = 10L,
                            KitId = 18,
                            PricePerItem = 4.85m
                        },
                        new
                        {
                            Id = 7,
                            ItemId = 7,
                            ItemsAmount = 3L,
                            KitId = 11,
                            PricePerItem = 146.03m
                        },
                        new
                        {
                            Id = 8,
                            ItemId = 4,
                            ItemsAmount = 5L,
                            KitId = 17,
                            PricePerItem = 5.36m
                        },
                        new
                        {
                            Id = 9,
                            ItemId = 4,
                            ItemsAmount = 1L,
                            KitId = 12,
                            PricePerItem = 29.33m
                        },
                        new
                        {
                            Id = 10,
                            ItemId = 5,
                            ItemsAmount = 10L,
                            KitId = 12,
                            PricePerItem = 14.82m
                        },
                        new
                        {
                            Id = 11,
                            ItemId = 4,
                            ItemsAmount = 8L,
                            KitId = 13,
                            PricePerItem = 84.11m
                        },
                        new
                        {
                            Id = 12,
                            ItemId = 1,
                            ItemsAmount = 1L,
                            KitId = 19,
                            PricePerItem = 116.63m
                        },
                        new
                        {
                            Id = 13,
                            ItemId = 3,
                            ItemsAmount = 8L,
                            KitId = 19,
                            PricePerItem = 51.50m
                        },
                        new
                        {
                            Id = 14,
                            ItemId = 10,
                            ItemsAmount = 2L,
                            KitId = 14,
                            PricePerItem = 26.45m
                        },
                        new
                        {
                            Id = 15,
                            ItemId = 6,
                            ItemsAmount = 8L,
                            KitId = 14,
                            PricePerItem = 22.19m
                        });
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltDescription = "occaecati",
                            FileUrl = "https://picsum.photos/640/480/?image=797"
                        },
                        new
                        {
                            Id = 2,
                            AltDescription = "enim",
                            FileUrl = "https://picsum.photos/640/480/?image=1045"
                        },
                        new
                        {
                            Id = 3,
                            AltDescription = "aut",
                            FileUrl = "https://picsum.photos/640/480/?image=860"
                        },
                        new
                        {
                            Id = 4,
                            AltDescription = "voluptas",
                            FileUrl = "https://picsum.photos/640/480/?image=493"
                        },
                        new
                        {
                            Id = 5,
                            AltDescription = "deleniti",
                            FileUrl = "https://picsum.photos/640/480/?image=862"
                        },
                        new
                        {
                            Id = 6,
                            AltDescription = "a",
                            FileUrl = "https://picsum.photos/640/480/?image=510"
                        },
                        new
                        {
                            Id = 7,
                            AltDescription = "sit",
                            FileUrl = "https://picsum.photos/640/480/?image=559"
                        },
                        new
                        {
                            Id = 8,
                            AltDescription = "non",
                            FileUrl = "https://picsum.photos/640/480/?image=67"
                        },
                        new
                        {
                            Id = 9,
                            AltDescription = "suscipit",
                            FileUrl = "https://picsum.photos/640/480/?image=632"
                        },
                        new
                        {
                            Id = 10,
                            AltDescription = "sit",
                            FileUrl = "https://picsum.photos/640/480/?image=671"
                        },
                        new
                        {
                            Id = 11,
                            AltDescription = "occaecati",
                            FileUrl = "https://picsum.photos/640/480/?image=433"
                        },
                        new
                        {
                            Id = 12,
                            AltDescription = "enim",
                            FileUrl = "https://picsum.photos/640/480/?image=81"
                        },
                        new
                        {
                            Id = 13,
                            AltDescription = "et",
                            FileUrl = "https://picsum.photos/640/480/?image=698"
                        },
                        new
                        {
                            Id = 14,
                            AltDescription = "soluta",
                            FileUrl = "https://picsum.photos/640/480/?image=896"
                        },
                        new
                        {
                            Id = 15,
                            AltDescription = "ratione",
                            FileUrl = "https://picsum.photos/640/480/?image=818"
                        },
                        new
                        {
                            Id = 16,
                            AltDescription = "molestias",
                            FileUrl = "https://picsum.photos/640/480/?image=445"
                        },
                        new
                        {
                            Id = 17,
                            AltDescription = "quia",
                            FileUrl = "https://picsum.photos/640/480/?image=688"
                        },
                        new
                        {
                            Id = 18,
                            AltDescription = "velit",
                            FileUrl = "https://picsum.photos/640/480/?image=515"
                        },
                        new
                        {
                            Id = 19,
                            AltDescription = "omnis",
                            FileUrl = "https://picsum.photos/640/480/?image=368"
                        },
                        new
                        {
                            Id = 20,
                            AltDescription = "distinctio",
                            FileUrl = "https://picsum.photos/640/480/?image=525"
                        });
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Item", b =>
                {
                    b.HasBaseType("QueflityMVC.Domain.Common.BasePurchasableEntity");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasIndex("CategoryId");

                    b.HasDiscriminator().HasValue("Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageId = 1,
                            Name = "Generic Wooden Cheese",
                            Price = 63.66m,
                            ShouldBeShown = false,
                            CategoryId = 5
                        },
                        new
                        {
                            Id = 2,
                            ImageId = 2,
                            Name = "Handmade Granite Car",
                            OrderNo = 4L,
                            Price = 23.89m,
                            ShouldBeShown = true,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageId = 3,
                            Name = "Handmade Wooden Chair",
                            OrderNo = 8L,
                            Price = 62.77m,
                            ShouldBeShown = true,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            ImageId = 4,
                            Name = "Intelligent Metal Pants",
                            Price = 44.04m,
                            ShouldBeShown = false,
                            CategoryId = 5
                        },
                        new
                        {
                            Id = 5,
                            ImageId = 5,
                            Name = "Ergonomic Plastic Bacon",
                            Price = 7.21m,
                            ShouldBeShown = false,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 6,
                            ImageId = 6,
                            Name = "Licensed Wooden Chair",
                            Price = 25.03m,
                            ShouldBeShown = false,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            ImageId = 7,
                            Name = "Incredible Fresh Mouse",
                            OrderNo = 1L,
                            Price = 86.35m,
                            ShouldBeShown = true,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            ImageId = 8,
                            Name = "Licensed Plastic Gloves",
                            OrderNo = 2L,
                            Price = 66.67m,
                            ShouldBeShown = true,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 9,
                            ImageId = 9,
                            Name = "Generic Concrete Salad",
                            Price = 94.91m,
                            ShouldBeShown = false,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 10,
                            ImageId = 10,
                            Name = "Ergonomic Metal Shirt",
                            OrderNo = 9L,
                            Price = 4.81m,
                            ShouldBeShown = true,
                            CategoryId = 3
                        });
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Kit", b =>
                {
                    b.HasBaseType("QueflityMVC.Domain.Common.BasePurchasableEntity");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.HasIndex("ItemId");

                    b.HasDiscriminator().HasValue("Kit");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            ImageId = 11,
                            Name = "Awesome Granite Towels",
                            OrderNo = 5L,
                            Price = 438.09m,
                            ShouldBeShown = true,
                            Description = "Consectetur vitae omnis enim rem."
                        },
                        new
                        {
                            Id = 12,
                            ImageId = 12,
                            Name = "Practical Rubber Sausages",
                            OrderNo = 0L,
                            Price = 177.53m,
                            ShouldBeShown = true,
                            Description = "Eius accusamus dignissimos perspiciatis impedit."
                        },
                        new
                        {
                            Id = 13,
                            ImageId = 13,
                            Name = "Fantastic Concrete Shirt",
                            Price = 672.88m,
                            ShouldBeShown = false,
                            Description = "Voluptatem qui est sint aut dolores ut error id sint."
                        },
                        new
                        {
                            Id = 14,
                            ImageId = 14,
                            Name = "Rustic Cotton Chair",
                            OrderNo = 7L,
                            Price = 230.42m,
                            ShouldBeShown = true,
                            Description = "Doloribus non perspiciatis."
                        },
                        new
                        {
                            Id = 15,
                            ImageId = 15,
                            Name = "Incredible Wooden Car",
                            Price = 0m,
                            ShouldBeShown = false,
                            Description = "Possimus eligendi et et error."
                        },
                        new
                        {
                            Id = 16,
                            ImageId = 16,
                            Name = "Fantastic Cotton Chair",
                            Price = 0m,
                            ShouldBeShown = false,
                            Description = "Totam optio quia reiciendis nam."
                        },
                        new
                        {
                            Id = 17,
                            ImageId = 17,
                            Name = "Sleek Wooden Keyboard",
                            Price = 570.13m,
                            ShouldBeShown = false,
                            Description = "Blanditiis dolorem at ut."
                        },
                        new
                        {
                            Id = 18,
                            ImageId = 18,
                            Name = "Ergonomic Frozen Gloves",
                            Price = 257.84m,
                            ShouldBeShown = false,
                            Description = "Debitis et eius dolores eaque sint cum sint."
                        },
                        new
                        {
                            Id = 19,
                            ImageId = 19,
                            Name = "Awesome Rubber Chair",
                            OrderNo = 6L,
                            Price = 886.38m,
                            ShouldBeShown = true,
                            Description = "Nobis adipisci perspiciatis aut enim."
                        },
                        new
                        {
                            Id = 20,
                            ImageId = 20,
                            Name = "Ergonomic Concrete Mouse",
                            OrderNo = 3L,
                            Price = 0m,
                            ShouldBeShown = true,
                            Description = "Nulla aut debitis quo qui harum doloribus."
                        });
                });

            modelBuilder.Entity("ComponentItem", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.Component", null)
                        .WithMany()
                        .HasForeignKey("ComponentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueflityMVC.Domain.Models.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueflityMVC.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QueflityMVC.Domain.Common.BasePurchasableEntity", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Element", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.Item", "Item")
                        .WithMany("SetElements")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QueflityMVC.Domain.Models.Kit", "Kit")
                        .WithMany("Elements")
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Kit");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Item", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Kit", b =>
                {
                    b.HasOne("QueflityMVC.Domain.Models.Item", null)
                        .WithMany("Kits")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Item", b =>
                {
                    b.Navigation("Kits");

                    b.Navigation("SetElements");
                });

            modelBuilder.Entity("QueflityMVC.Domain.Models.Kit", b =>
                {
                    b.Navigation("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
