# We choose exact tag (not 'latest'), to be sure that new version wont break creating image
FROM mcr.microsoft.com/mssql/server:2022-latest

ENV SA_PASSWORD Lf5892dENz
ENV ACCEPT_EULA Y
ENV MSSQL_PID Express

EXPOSE 1433