version: '3.4'

services:
  queflitymvc.web:
    image: ${DOCKER_REGISTRY-}queflitymvcweb
    build:
      context: .
      dockerfile: QueflityMVC/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      - DB_CONNECTION_STRING=Server=queflity_database;Database=QueflityDb;User Id=SA;Password=Lf5892dENz;MultipleActiveResultSets=true;TrustServerCertificate=true
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
  sql:
    container_name: queflity_database
    build:
      context: .
      dockerfile: Database/Dockerfile
    ports:
      - "1433:1433"