version: '3.4'

services:
  queflitymvc.web:
    image: ${DOCKER_REGISTRY-}queflitymvcweb
    build:
      context: .
      dockerfile: QueflityMVC/Dockerfile
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      - ASPNETCORE_URLS=https://+:8001;http://+:8000
  sql:
    container_name: queflity_database
    build:
      context: .
      dockerfile: Database/Dockerfile
    ports:
      - "1433:1433"