name: Build & Test 🧪

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 📦
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies 📂
        run: dotnet restore ./src/QueflityMVC.sln

      - name: Build 🧱
        run: dotnet build ./src/QueflityMVC.sln --configuration Release --no-restore

      - name: Test 🧪
        run: dotnet test ./src/QueflityMVC.sln --configuration Release --no-build
